# Generated by Django 4.2.7 on 2026-05-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='quotes/'),
        ),
    ]
