# Generated by Django 4.2.7 on 2026-05-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quote_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='document',
        ),
        migrations.CreateModel(
            name='QuoteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='quotes/')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.quote')),
            ],
        ),
    ]
