# Generated by Django 4.2.7 on 2026-05-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_portfolio_remove_post_image_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_after',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_before',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='posts/'),
        ),
    ]
