# Generated by Django 4.2.7 on 2026-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_image_after_post_image_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='surface_m2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
