# Generated by Django 4.2.7 on 2026-05-14 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_setting_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_before', models.ImageField(blank=True, max_length=255, null=True, upload_to='portfolio/')),
                ('image_after', models.ImageField(blank=True, max_length=255, null=True, upload_to='portfolio/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_pairs', to='api.portfolio')),
            ],
        ),
    ]
